// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Head() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><title>Text Viewer</title><script>\n\t\t// Called when the \"Mark as Seen\" button is clicked\n\t\tfunction markAsSeen(rowId) {\n\t\t    fetch('/mark-seen?id=' + rowId, {\n\t\t\tmethod: 'POST'\n\t\t    })\n\t\t    .then(response => response.json())\n\t\t    .then(data => {\n\t\t\tif (data.success) {\n\t\t\t    document.getElementById('status-' + rowId).textContent = 'seen';\n\t\t\t    // Disable the button and change text\n\t\t\t    const btn = document.getElementById('seen-btn-' + rowId);\n\t\t\t    btn.disabled = true;\n\t\t\t    btn.textContent = \"Seen\";\n\t\t\t} else {\n\t\t\t    alert('Failed to mark as seen: ' + data.error);\n\t\t\t}\n\t\t    })\n\t\t    .catch(error => {\n\t\t\tconsole.error('Error marking as seen:', error);\n\t\t\talert('Error marking as seen');\n\t\t    });\n\t\t}\n\n\t\t// OnChange for the month picker. Redirect to the same page with \"?month=YYYY-MM\"\n\t\tfunction onMonthChange(selectElem) {\n\t\t    const monthVal = selectElem.value;\n\t\t    // If empty, remove the ?month= param\n\t\t    if (monthVal === \"\") {\n\t\t\twindow.location.href = \"/\";\n\t\t    } else {\n\t\t\twindow.location.href = \"/?month=\" + monthVal;\n\t\t    }\n\t\t}\n\t    </script></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
